# Generated by Django 4.2.2 on 2023-07-10 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_subscription_advertise_subscription_new_films_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'طرح های اشتراکی', 'verbose_name_plural': 'طرح اشتراکی'},
        ),
        migrations.AlterField(
            model_name='user',
            name='Subscription_plan',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Subscription', to='accounts.subscription', verbose_name='طرح اشتراک'),
        ),
    ]
