# Generated by Django 4.2.2 on 2023-07-23 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='اسلاگ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ آپلود دسته بندی')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ به روز رسانی دسته بندی')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب ها',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('meta_description', models.CharField(max_length=3000, verbose_name='متادیسکریپشن')),
                ('image', models.ImageField(null=True, upload_to='images/thumbnails', verbose_name='تصویر ویدئو')),
                ('age', models.CharField(blank=True, choices=[('20', '+20'), ('14', '+14'), ('10', '+10')], max_length=10, null=True, verbose_name='رده سنی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود ویدئو')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ به روز رسانی ویدئو')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='اسلاگ')),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده مقاله')),
                ('tag', models.ManyToManyField(related_name='blogs', to='blog.tag', verbose_name='برچسب ها')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقاله ها',
                'ordering': ['-created_at'],
            },
        ),
    ]
