# Generated by Django 4.2.2 on 2023-07-11 13:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30, verbose_name="عنوان")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        null=True,
                        unique=True,
                        verbose_name="اسلاگ",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="تاریخ آپلود دسته بندی",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="تاریخ به روز رسانی دسته بندی",
                    ),
                ),
            ],
            options={
                "verbose_name": "دسته بندی",
                "verbose_name_plural": "دسته بندی\u200cها",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="عنوان")),
                ("description", models.TextField(verbose_name="توضیحات")),
                (
                    "meta_description",
                    models.CharField(max_length=3000, verbose_name="متادیسکریپشن"),
                ),
                (
                    "image",
                    models.ImageField(
                        null=True,
                        upload_to="images/thumbnails",
                        verbose_name="تصویر ویدئو",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        null=True,
                        upload_to="videos/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["MOV", "avi", "mp4", "webm", "mkv"]
                            )
                        ],
                        verbose_name="ویدئو",
                    ),
                ),
                (
                    "like_count",
                    models.BigIntegerField(
                        default="0", verbose_name="تعداد لایک\u200cها"
                    ),
                ),
                (
                    "age",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("فارسی", "فارسی"),
                            ("انگلیسی", "انگلیسی"),
                            ("آلمانی", "آلمانی"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="رده سنی",
                    ),
                ),
                (
                    "time",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="مدت زمان"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ آپلود ویدئو"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="تاریخ به روز رسانی ویدئو",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        null=True,
                        unique=True,
                        verbose_name="اسلاگ",
                    ),
                ),
                (
                    "category",
                    models.ManyToManyField(
                        related_name="videos",
                        to="video.category",
                        verbose_name="دسته بندی",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="سازنده محتوا",
                    ),
                ),
                (
                    "favorites",
                    models.ManyToManyField(
                        blank=None,
                        default=None,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مورد علاقه\u200cها",
                    ),
                ),
                (
                    "likes",
                    models.ManyToManyField(
                        blank=True,
                        default=None,
                        related_name="likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ویدئو",
                "verbose_name_plural": "ویدئوها",
                "ordering": ["-created_at"],
            },
        ),
    ]
