# Generated by Django 4.2.2 on 2023-07-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0003_alter_video_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="age",
            field=models.CharField(
                blank=True,
                choices=[("20", "بزرگسال"), ("14", "نوجوان"), ("10", "کودک")],
                max_length=10,
                null=True,
                verbose_name="رده سنی",
            ),
        ),
    ]
