# Generated by Django 4.2.2 on 2023-07-27 18:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0011_serial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serial",
            name="number",
        ),
    ]
