# Generated by Django 4.2.2 on 2023-07-28 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0016_notification_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="serial",
            name="season",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seasons",
                to="video.serial",
                verbose_name="فصل",
            ),
        ),
    ]
