# Generated by Django 4.2.2 on 2023-07-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0019_alter_serial_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/comment", verbose_name="عکس"
            ),
        ),
    ]
